---
- name: Install Jenkins on Ubuntu servers
  hosts: jenkins-servers
  become: yes
  tasks:
    - name: Install Java (required for Jenkins)
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes
 
    - name: Download Jenkins GPG key
      get_url:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'
 
    - name: Add Jenkins apt repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/"
        state: present
        filename: jenkins
 
    - name: Update apt cache
      apt:
        update_cache: yes

      ---
- name: Install Jenkins on Ubuntu servers
  hosts: jenkins-servers
  become: yes
  tasks:
    - name: Install Java (required for Jenkins)
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes
 
    - name: Download Jenkins GPG key
      get_url:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'
 
    - name: Add Jenkins apt repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/"
        state: present
        filename: jenkins
 
    - name: Update apt cache
      apt:
        update_cache: yes
    ---
- name: Install Jenkins on Ubuntu servers
  hosts: jenkins-servers
  become: yes
  tasks:
    - name: Install Java (required for Jenkins)
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes
 
    - name: Download Jenkins GPG key
      get_url:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'
 
    - name: Add Jenkins apt repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/"
        state: present
        filename: jenkins
 
    - name: Update apt cache
      apt:
        update_cache: yes
 
---
- name: Install Jenkins on Ubuntu servers
  hosts: jenkins-servers
  become: yes
  tasks:
    - name: Install Java (required for Jenkins)
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes
 
    - name: Download Jenkins GPG key
      get_url:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'
 
    - name: Add Jenkins apt repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/"
        state: present
        filename: jenkins
 
    - name: Update apt cache
      apt:
        update_cache: yes
        
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
 
    - name: Ensure Jenkins is started and enabled
      systemd:
        name: jenkins
        enabled: yes
        state: started
 
    - name: Print Jenkins service status
      command: systemctl status jenkins
      register: result
      ignore_errors: true
 
    - debug:
        var: result.stdout_lines

 
